'use client';

import { useState, useEffect, useCallback } from 'react';
import {
  X, Copy, Check, FileJson, CheckCircle,
  AlertTriangle, AlertCircle, RefreshCw, ChevronDown, ChevronUp,
} from 'lucide-react';
import { validateBlogImport } from '@/lib/validate-blog-import';
import { EXAMPLE_BLOG_JSON, BLOG_CLAUDE_PROMPT } from '@/lib/blog-import-example';

// ── Shared styles ─────────────────────────────────────────────────────────────
const S = {
  textarea: {
    width: '100%',
    minHeight: '260px',
    padding: '14px',
    border: '1.5px solid #E2E8F0',
    borderRadius: '12px',
    fontSize: '12px',
    fontFamily: '"Cascadia Code", "Fira Code", "Consolas", monospace',
    color: '#0F172A',
    background: '#FAFBFF',
    resize: 'vertical',
    outline: 'none',
    boxSizing: 'border-box',
    lineHeight: 1.6,
  },
  btnPrimary: {
    display: 'inline-flex', alignItems: 'center', gap: '7px',
    padding: '10px 20px', borderRadius: '10px',
    background: 'linear-gradient(135deg, #0EA5E9 0%, #06B6D4 100%)',
    color: '#FFFFFF', border: 'none', fontSize: '13px', fontWeight: 700,
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(14,165,233,0.28)',
  },
  btnSecondary: {
    display: 'inline-flex', alignItems: 'center', gap: '6px',
    padding: '9px 16px', borderRadius: '10px',
    background: '#F8FAFF', color: '#334155', border: '1.5px solid #E2E8F0',
    fontSize: '13px', fontWeight: 600, cursor: 'pointer',
  },
  btnGreen: {
    display: 'inline-flex', alignItems: 'center', gap: '7px',
    padding: '10px 20px', borderRadius: '10px',
    background: 'linear-gradient(135deg, #059669 0%, #10B981 100%)',
    color: '#FFFFFF', border: 'none', fontSize: '13px', fontWeight: 700,
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(5,150,105,0.25)',
  },
  disabled: { opacity: 0.45, cursor: 'not-allowed', pointerEvents: 'none' },
};

// ── Small helpers ─────────────────────────────────────────────────────────────

function CopyButton({ text, label = 'Kopieren', labelDone = 'Kopiert' }) {
  const [copied, setCopied] = useState(false);
  async function go() {
    try { await navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 2200); }
    catch {}
  }
  return (
    <button onClick={go} style={{ ...S.btnSecondary, padding: '6px 12px', fontSize: '12px' }}>
      {copied ? <><Check size={12} strokeWidth={2.5} color="#059669" />{labelDone}</> : <><Copy size={12} strokeWidth={2} />{label}</>}
    </button>
  );
}

function ValidationPanel({ errors, warnings }) {
  if (!errors.length && !warnings.length) return null;
  return (
    <div style={{ marginTop: '14px', display: 'flex', flexDirection: 'column', gap: '10px' }}>
      {errors.length > 0 && (
        <div style={{ padding: '14px 16px', borderRadius: '12px', background: '#FEF2F2', border: '1px solid #FECACA' }}>
          <p style={{ fontSize: '12px', fontWeight: 700, color: '#DC2626', marginBottom: '8px' }}>
            {errors.length} Fehler – Importieren nicht möglich
          </p>
          <ul style={{ margin: 0, padding: '0 0 0 16px' }}>
            {errors.map((e, i) => <li key={i} style={{ fontSize: '12px', color: '#B91C1C', marginBottom: '3px' }}>{e}</li>)}
          </ul>
        </div>
      )}
      {warnings.length > 0 && (
        <div style={{ padding: '14px 16px', borderRadius: '12px', background: '#FFFBEB', border: '1px solid #FDE68A' }}>
          <p style={{ fontSize: '12px', fontWeight: 700, color: '#D97706', marginBottom: '8px' }}>
            {warnings.length} Hinweis{warnings.length > 1 ? 'e' : ''} (kein Blocker)
          </p>
          <ul style={{ margin: 0, padding: '0 0 0 16px' }}>
            {warnings.map((w, i) => <li key={i} style={{ fontSize: '12px', color: '#92400E', marginBottom: '3px' }}>{w}</li>)}
          </ul>
        </div>
      )}
    </div>
  );
}

function PreviewRow({ label, value }) {
  if (!value && value !== false) return null;
  return (
    <div style={{ display: 'flex', gap: '12px', padding: '7px 0', borderBottom: '1px solid #F1F5F9' }}>
      <div style={{ width: '160px', flexShrink: 0, fontSize: '12px', fontWeight: 600, color: '#64748B' }}>{label}</div>
      <div style={{ fontSize: '12px', color: '#0F172A', flex: 1, wordBreak: 'break-all' }}>
        {typeof value === 'boolean' ? (value ? 'Ja' : 'Nein') : String(value).slice(0, 200)}
      </div>
    </div>
  );
}

function PreviewPanel({ result }) {
  const n = result.normalized;
  const auto = result.autogenerated ?? [];
  return (
    <div style={{ padding: '16px 18px', borderRadius: '12px', background: '#F0FDF4', border: '1.5px solid #BBF7D0', marginTop: '14px' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '14px' }}>
        <CheckCircle size={16} strokeWidth={2.5} color="#059669" />
        <span style={{ fontSize: '14px', fontWeight: 700, color: '#065F46' }}>JSON gültig – Vorschau</span>
        {auto.length > 0 && (
          <span style={{ fontSize: '11px', color: '#7C3AED', fontWeight: 600 }}>
            · {auto.length} Feld{auto.length > 1 ? 'er' : ''} automatisch generiert
          </span>
        )}
      </div>
      <div style={{ background: '#FFFFFF', borderRadius: '10px', border: '1px solid #D1FAE5', padding: '12px 16px' }}>
        <PreviewRow label="Titel"          value={n.title} />
        <PreviewRow label="Slug"           value={`/reiseblog/${n.slug}`} />
        <PreviewRow label="Kategorie"      value={n.category} />
        <PreviewRow label="Destination"    value={[n.destination, n.country].filter(Boolean).join(', ')} />
        <PreviewRow label="Autor"          value={n.author} />
        <PreviewRow label="Lesezeit"       value={n.reading_time} />
        <PreviewRow label="Status"         value={n.status} />
        <PreviewRow label="Featured"       value={n.featured} />
        <PreviewRow label="Excerpt"        value={n.excerpt} />
        <PreviewRow label="SEO-Titel"      value={n.seo_title} />
        <PreviewRow label="SEO-Beschreibung" value={n.seo_description} />
        <PreviewRow label="Tags"           value={n.tags} />
        <PreviewRow label="Inhaltsverz."   value={`${(n._tableOfContents ?? []).length} Einträge`} />
        <PreviewRow label="Inhaltsbereiche" value={`${(n._contentSections ?? []).length} Abschnitte`} />
        <PreviewRow label="FAQ"            value={`${(n._faq ?? []).length} Fragen`} />
        <PreviewRow label="Cover-Bild"     value={n.cover_image_url || '(keines – separat hochladen)'} />
      </div>
      {result.warnings.length > 0 && (
        <div style={{ marginTop: '12px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '6px' }}>
            <AlertTriangle size={12} strokeWidth={2} color="#D97706" />
            <span style={{ fontSize: '12px', fontWeight: 700, color: '#D97706' }}>{result.warnings.length} Hinweis{result.warnings.length > 1 ? 'e' : ''}</span>
          </div>
          <ul style={{ margin: 0, padding: '0 0 0 16px' }}>
            {result.warnings.map((w, i) => <li key={i} style={{ fontSize: '12px', color: '#92400E', marginBottom: '2px' }}>{w}</li>)}
          </ul>
        </div>
      )}
    </div>
  );
}

// ── Main Modal ────────────────────────────────────────────────────────────────
export default function BlogImportModal({ open, onClose, onImport }) {
  const [rawJson,  setRawJson]  = useState('');
  const [result,   setResult]   = useState(null);
  const [checked,  setChecked]  = useState(false);
  const [promptOpen, setPromptOpen] = useState(false);
  const [confirmPending, setConfirmPending] = useState(false);

  // Close on Escape
  useEffect(() => {
    function onKey(e) { if (e.key === 'Escape') { onClose(); } }
    if (open) window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [open, onClose]);

  // Reset when reopened
  useEffect(() => {
    if (open) {
      setRawJson('');
      setResult(null);
      setChecked(false);
      setConfirmPending(false);
      setPromptOpen(false);
    }
  }, [open]);

  const handleValidate = useCallback(() => {
    const r = validateBlogImport(rawJson);
    setResult(r);
    setChecked(true);
    setConfirmPending(false);
  }, [rawJson]);

  const handleExample = useCallback(() => {
    setRawJson(JSON.stringify(EXAMPLE_BLOG_JSON, null, 2));
    setResult(null);
    setChecked(false);
    setConfirmPending(false);
  }, []);

  function handleConfirmImport() {
    if (result?.valid && result.normalized) {
      onImport(result.normalized);
    }
  }

  if (!open) return null;

  const isValid = result?.valid === true;

  return (
    <div
      style={{
        position: 'fixed', inset: 0, zIndex: 500,
        background: 'rgba(15,23,42,0.50)',
        display: 'flex', alignItems: 'flex-start', justifyContent: 'center',
        padding: '32px 16px',
        overflowY: 'auto',
      }}
      onClick={e => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div style={{
        background: '#FFFFFF',
        borderRadius: '20px',
        width: '100%',
        maxWidth: '740px',
        boxShadow: '0 24px 80px rgba(15,23,42,0.22)',
        overflow: 'hidden',
        marginBottom: '32px',
      }}>
        {/* ── Header ── */}
        <div style={{
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          padding: '20px 24px',
          borderBottom: '1.5px solid #F1F5F9',
          background: '#FAFBFF',
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <div style={{
              width: '36px', height: '36px', borderRadius: '10px',
              background: '#EFF6FF', border: '1.5px solid #BAE6FD',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              <FileJson size={18} color="#0EA5E9" strokeWidth={2} />
            </div>
            <div>
              <div style={{ fontSize: '16px', fontWeight: 800, color: '#0F172A' }}>JSON importieren</div>
              <div style={{ fontSize: '12px', color: '#64748B', marginTop: '1px' }}>
                JSON einfügen → Felder werden automatisch befüllt
              </div>
            </div>
          </div>
          <button onClick={onClose} style={{
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            width: '32px', height: '32px', borderRadius: '8px',
            border: '1.5px solid #E2E8F0', background: '#FFFFFF',
            color: '#64748B', cursor: 'pointer',
          }}>
            <X size={16} strokeWidth={2.5} />
          </button>
        </div>

        <div style={{ padding: '24px' }}>

          {/* ── Steps ── */}
          <div style={{ display: 'flex', gap: '6px', marginBottom: '24px', flexWrap: 'wrap' }}>
            {['1 Prompt kopieren', '2 JSON einfügen', '3 JSON prüfen', '4 Importieren'].map((step, i) => (
              <span key={step} style={{
                fontSize: '11px', fontWeight: 700, padding: '4px 10px', borderRadius: '6px',
                background: i < 2 ? '#F0F9FF' : i === 2 ? (checked ? (isValid ? '#F0FDF4' : '#FEF2F2') : '#F0F9FF') : (isValid ? '#F0FDF4' : '#F8FAFF'),
                color: i < 2 ? '#0284C7' : i === 2 ? (checked ? (isValid ? '#059669' : '#DC2626') : '#0284C7') : (isValid ? '#059669' : '#94A3B8'),
                border: `1px solid ${i < 2 ? '#BAE6FD' : i === 2 ? (checked ? (isValid ? '#A7F3D0' : '#FECACA') : '#BAE6FD') : (isValid ? '#A7F3D0' : '#E2E8F0')}`,
              }}>
                {step}
              </span>
            ))}
          </div>

          {/* ── 1. Claude Prompt ── */}
          <div style={{ border: '1.5px solid #E2E8F0', borderRadius: '14px', marginBottom: '20px', overflow: 'hidden' }}>
            <button
              onClick={() => setPromptOpen(p => !p)}
              style={{
                width: '100%', padding: '14px 18px',
                display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                background: '#FAFBFF', border: 'none', cursor: 'pointer',
                borderBottom: promptOpen ? '1.5px solid #E2E8F0' : 'none',
              }}
            >
              <span style={{ fontSize: '14px', fontWeight: 700, color: '#0F172A' }}>
                1. Prompt für Claude
              </span>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <span style={{ fontSize: '12px', color: '#64748B' }}>Vorlage kopieren und bei Claude einfügen</span>
                {promptOpen ? <ChevronUp size={15} strokeWidth={2} color="#64748B" /> : <ChevronDown size={15} strokeWidth={2} color="#64748B" />}
              </div>
            </button>
            {promptOpen && (
              <div style={{ padding: '16px 18px' }}>
                <pre style={{
                  fontSize: '12px',
                  fontFamily: '"Cascadia Code", "Fira Code", "Consolas", monospace',
                  background: '#F8FAFF', border: '1px solid #E2E8F0',
                  borderRadius: '10px', padding: '14px',
                  margin: '0 0 12px',
                  whiteSpace: 'pre-wrap', color: '#334155', lineHeight: 1.65,
                }}>
                  {BLOG_CLAUDE_PROMPT}
                </pre>
                <CopyButton text={BLOG_CLAUDE_PROMPT} label="Prompt kopieren" labelDone="Kopiert" />
              </div>
            )}
          </div>

          {/* ── 2+3. JSON Textarea ── */}
          <div style={{ marginBottom: '20px' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '10px' }}>
              <label style={{ fontSize: '14px', fontWeight: 700, color: '#0F172A' }}>
                2. Blog-Artikel JSON einfügen
              </label>
              <button
                onClick={handleExample}
                style={{ ...S.btnSecondary, padding: '6px 12px', fontSize: '12px' }}
              >
                Beispiel-JSON anzeigen
              </button>
            </div>

            <textarea
              value={rawJson}
              onChange={e => {
                setRawJson(e.target.value);
                setChecked(false);
                setResult(null);
                setConfirmPending(false);
              }}
              placeholder={'{\n  "title": "Dein Artikeltitel",\n  "slug": "dein-artikel-slug",\n  ...\n}'}
              style={S.textarea}
              spellCheck={false}
              autoComplete="off"
            />

            <div style={{ display: 'flex', gap: '10px', marginTop: '12px', flexWrap: 'wrap', alignItems: 'center' }}>
              <button
                onClick={handleValidate}
                disabled={!rawJson.trim()}
                style={{ ...S.btnPrimary, ...(!rawJson.trim() ? S.disabled : {}) }}
              >
                <CheckCircle size={14} strokeWidth={2.5} />
                JSON prüfen
              </button>
              {rawJson.trim() && (
                <button
                  onClick={() => { setRawJson(''); setResult(null); setChecked(false); setConfirmPending(false); }}
                  style={{ ...S.btnSecondary, color: '#94A3B8' }}
                >
                  Leeren
                </button>
              )}
              {rawJson.trim() && (
                <CopyButton text={rawJson} label="JSON kopieren" />
              )}
            </div>

            {/* Validation errors/warnings */}
            {checked && result && <ValidationPanel errors={result.errors ?? []} warnings={result.warnings ?? []} />}
          </div>

          {/* ── 4. Preview + Confirm ── */}
          {isValid && result.normalized && (
            <>
              <PreviewPanel result={result} />

              <div style={{
                marginTop: '20px',
                padding: '18px 20px',
                background: '#FAFBFF',
                borderRadius: '14px',
                border: '1.5px solid #E2E8F0',
              }}>
                {!confirmPending ? (
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '12px' }}>
                    <p style={{ fontSize: '13px', color: '#475569', margin: 0 }}>
                      Bereit zum Importieren – vorhandene Felder werden überschrieben.
                    </p>
                    <button
                      onClick={() => setConfirmPending(true)}
                      style={S.btnGreen}
                    >
                      <CheckCircle size={14} strokeWidth={2.5} />
                      Felder importieren
                    </button>
                  </div>
                ) : (
                  <div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '14px' }}>
                      <AlertTriangle size={16} strokeWidth={2} color="#D97706" />
                      <span style={{ fontSize: '14px', fontWeight: 700, color: '#92400E' }}>
                        Vorhandene Felder werden überschrieben. Fortfahren?
                      </span>
                    </div>
                    <p style={{ fontSize: '13px', color: '#64748B', marginBottom: '16px' }}>
                      Alle ausgefüllten Formularfelder werden durch die Werte aus dem JSON ersetzt.
                      Du kannst danach noch manuell bearbeiten, bevor du speicherst.
                    </p>
                    <div style={{ display: 'flex', gap: '10px' }}>
                      <button onClick={() => setConfirmPending(false)} style={S.btnSecondary}>
                        Abbrechen
                      </button>
                      <button onClick={handleConfirmImport} style={S.btnGreen}>
                        <CheckCircle size={14} strokeWidth={2.5} />
                        Ja, Felder überschreiben
                      </button>
                    </div>
                  </div>
                )}
              </div>

              {/* Image hint */}
              <div style={{
                marginTop: '12px',
                display: 'flex', alignItems: 'flex-start', gap: '8px',
                padding: '10px 14px',
                background: '#FFF7ED',
                border: '1px solid #FED7AA',
                borderRadius: '10px',
                fontSize: '12px', color: '#92400E',
              }}>
                <AlertCircle size={14} strokeWidth={2} color="#D97706" style={{ flexShrink: 0, marginTop: '1px' }} />
                <span>
                  Cover- und Hero-Bild werden <strong>nicht</strong> über JSON importiert (außer das JSON enthält URLs).
                  Lade das Bild nach dem Import im <strong>Medien-Tab</strong> hoch.
                </span>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
